### ISSUE TITLE
Colors differ from original scheme

### ISSUE THREAD

**Issue by jzbor** [casonadams/base16-apprentice-scheme#1]
This repo differs quite substantially from the original Apprentice scheme. For example the original red color (`#AF5F5F`) is now gray (`#303030`). Is this on purpose?

**Comment by casonadams** [comment]
Feel free to correct and open an MR

**Comment by casonadams** [comment]
@jzbor have a look at https://github.com/casonadams/alacritty-shell might be something you might want to use.
